### ISSUE TITLE
"yarn start" having error

### ISSUE THREAD

**Issue by linghuccc** [nand2/evm-browser#10]
Step 1: "git clone" this repository;
Step 2: "yarn install", install all the dependencies;
Step 3: "yarn start", will report below error:
![evm](https://github.com/user-attachments/assets/9f2ea7bd-e3e7-46c4-8cd5-a52ddb426225)

**Comment by nand2** [comment]
Hi!

It looks like this is an issue with electron and your Linux/Mac distribution; searching for "electron libnss3.so" I can find several hits about this issue and electron/chromium projects, such as https://stackoverflow.com/questions/58134793/error-while-loading-shared-libraries-libnss3-so-while-running-gtlab-ci-job-to

Let me know if you find out which was the issue in your distribution.
